name: WF

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    stops:
      - uses: actions/checkout@v3
      - name: Set up JDK 15
        uses: actions/setup-java@v2
        with:
          java-version: '15'
          distribution: 'adopt'